language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ah4' ]; then cd .. && eval "mv $currentfolder generator-ah4" && cd generator-ah4; fi

